update workflow so it accounts for package.json file non-existent case

diff --git a/.github/workflows/auto_test.yml b/.github/workflows/auto_test.yml
--- a/.github/workflows/auto_test.yml
+++ b/.github/workflows/auto_test.yml
@@ -19,7 +19,15 @@ jobs:   # run tests specified in test/
           node-version: '18.17.1' # specify the Node.js version: same version as eceprog
 
       - name: Install dependencies
-        run: npm install
+        # only install dependencies if package.json is found
+        # stops the workflow if package.json is not found
+        run: |
+          if [-f package.json]; then
+            npm install
+          else
+            echo "package.json not found in main branch"
+            exit 1
+          fi
         
       - name: Setup environment
         # $GITHUB_ENV: .env file for github actions, this step configures LOG_FILE env variable
diff --git a/.github/workflows/lint.yml b/.github/workflows/lint.yml
--- a/.github/workflows/lint.yml
+++ b/.github/workflows/lint.yml
@@ -24,10 +24,16 @@ jobs:
         with:
           node-version: '18'
 
-      # Install dependencies, including ESLint and Airbnb config
       - name: Install dependencies
+        # only install dependencies if package.json is found
+        # stops the workflow if package.json is not found
         run: |
-          npm install
+          if [-f package.json]; then
+            npm install
+          else
+            echo "package.json not found in main branch"
+            exit 1
+          fi
 
       # Run ESLint to check for style and linting issues
       - name: Run ESLint
